Repository innovationnorway/terraform-provider-databricks, pull requests merged in 2020-04, with the labels that each got.

#34 Update code to follow some conventions
  .github/workflows/test.yml
  .golangci.yml
  CHANGELOG.md
  databricks/config.go
  databricks/data_source_databricks_cluster.go
  databricks/data_source_databricks_cluster_test.go
  databricks/data_source_databricks_group_members.go
  databricks/data_source_databricks_group_members_test.go
  databricks/resource_databricks_cluster.go
  databricks/resource_databricks_cluster_test.go
  databricks/resource_databricks_group.go
  databricks/resource_databricks_group_member.go
  databricks/resource_databricks_group_member_test.go
  databricks/resource_databricks_group_test.go
  databricks/resoure_databricks_workspace_import_test.go
  go.mod
  go.sum
Labels: enhancement

#39 Provider: Support for specifying the workspace organization ID
  CHANGELOG.md
  databricks/config.go
  databricks/provider.go
  go.mod
  go.sum
  website/docs/index.html.markdown
Labels: enhancement

#42 Fix errors in `aws_attributes`
  databricks/resource_databricks_cluster.go
  databricks/resource_databricks_cluster_test.go
Labels: bug

#43 Add example for AWS
  examples/aws/main.tf
  examples/aws/variables.tf
Labels: documentation, enhancement

#44 Remove unnecessary variable assignments
  databricks/resource_databricks_cluster.go
  databricks/resource_databricks_group.go
Labels: enhancement

#54 New Resource: `databricks_dbfs_mkdirs`
  CHANGELOG.md
  databricks/config.go
  databricks/provider.go
  databricks/resource_databricks_dbfs_mkdirs.go
  databricks/resource_databricks_dbfs_mkdirs_test.go
  go.mod
  go.sum
  website/databricks.erb
  website/docs/r/databricks_dbfs_mkdirs.html.markdown
Labels: enhancement

#55 New Resource: `databricks_dbfs_upload`
  CHANGELOG.md
  databricks/provider.go
  databricks/resource_databricks_dbfs_upload.go
  databricks/resource_databricks_dbfs_upload_test.go
  website/databricks.erb
  website/docs/r/databricks_dbfs_upload.html.markdown
Labels: enhancement

#58 Adding the secrets resources
  databricks/config.go
  databricks/provider.go
  databricks/resource_databricks_secret.go
  databricks/resource_databricks_secret_acls.go
  databricks/resource_databricks_secret_scope.go
  go.mod
  go.sum
Labels: enhancement

#60 Fixing Docker Image Typo
  databricks/data_source_databricks_cluster.go
  databricks/resource_databricks_cluster.go
Labels: bug

#62 Add simple test case for creating cluster with custom Docker image
  databricks/resource_databricks_cluster_test.go
Labels: enhancement
